#!/bin/bash
declare -A colors

### essentials ###
colors["reset"]="\033[0m"
colors["bold"]="\033[1m"
colors["light"]="\033[2m"
colors["italic"]="\033[3m"
colors["underline"]="\033[4m"
colors["highlight-white"]="\033[7m"
colors["strike-through"]="\033[9m"

### colors ###
# regulars
colors["black"]="\033[30m"
colors["red"]="\033[31m"
colors["green"]="\033[32m"
colors["yellow"]="\033[33m"
colors["blue"]="\033[34m"
colors["magenta"]="\033[35m"
colors["cyan"]="\033[36m"
colors["white"]="\033[37m"
colors["highlight-black"]="\033[40m"
colors["highlight-red"]="\033[41m"
colors["highlight-green"]="\033[42m"
colors["highlight-yellow"]="\033[43m"
colors["highlight-blue"]="\033[44m"
colors["highlight-magenta"]="\033[45m"
colors["highlight-cyan"]="\033[46m"
colors["highlight-white"]="\033[47m"

# bolds
colors["bold-black"]="\033[1;30m"
colors["bold-red"]="\033[1;31m"
colors["bold-green"]="\033[1;32m"
colors["bold-yellow"]="\033[1;33m"
colors["bold-blue"]="\033[1;34m"
colors["bold-magenta"]="\033[1;35m"
colors["bold-cyan"]="\033[1;36m"
colors["bold-white"]="\033[1;37m"
colors["bold-highlight-black"]="\033[1;40m"
colors["bold-highlight-red"]="\033[1;41m"
colors["bold-highlight-green"]="\033[1;42m"
colors["bold-highlight-yellow"]="\033[1;43m"
colors["bold-highlight-blue"]="\033[1;44m"
colors["bold-highlight-magenta"]="\033[1;45m"
colors["bold-highlight-cyan"]="\033[1;46m"
colors["bold-highlight-white"]="\033[1;47m"

# lights
colors["light-black"]="\033[90m"
colors["light-red"]="\033[91m"
colors["light-green"]="\033[92m"
colors["light-yellow"]="\033[93m"
colors["light-blue"]="\033[94m"
colors["light-magenta"]="\033[95m"
colors["light-cyan"]="\033[96m"
colors["light-white"]="\033[97m"
colors["light-highlight-black"]="\033[100m"
colors["light-highlight-red"]="\033[101m"
colors["light-highlight-green"]="\033[102m"
colors["light-highlight-yellow"]="\033[103m"
colors["light-highlight-blue"]="\033[104m"
colors["light-highlight-magenta"]="\033[105m"
colors["light-highlight-cyan"]="\033[106m"
colors["light-highlight-white"]="\033[107m"

howto() {
    printf "ansi is a tool to get ANSI escape color code for desired formatting.\n\n"

    printf "Usage:  ansi [ str1 str2 str3 ... ] -ah\n"
    printf "Base Colours:\n"
    printf "\tblack\n\tred\n\tgreen\n\tyellow\n\tblue\n\tmagenta\n\tcyan\n\twhite\n"

    printf "\n-a: "
    printf "Show all avaliable ANSI color codes.\n"
   
    printf "\n-h: "
    printf "Show this help text.\n"
}

err() {
    printf "${colors[red]}%s${colors[reset]}\n" "$1"
}

if [[ -z $1 ]]; then
    err "Please call with COLOR arument."
    howto
    exit 0

elif [[ $1 == "-h" ]]; then
    howto
    exit 1

elif [[ $1 == "-a" ]]; then
    for i in ${!colors[*]}
    do
        color=${colors[$i]}
        printf "${colors[$i]}The ANSI code for $i : %s ${colors[reset]}\n" "$color"
    done

else  
    pattern="$1"

    for i in ${@:2}
    do
        pattern+="\|$i"
    done

    matches=$(printf "%s\n" ${!colors[*]} | grep $pattern)

    if [[ -z $matches ]]; then
        err "Sorry, found no codes for search strings: $(echo $pattern | sed 's/\\|/, /g')"
    else
        for i in $matches
        do
            printf "${colors[$i]}The ANSI code for %s: %s ${colors[reset]}\n" "$i" "${colors[$i]}"
        done
        echo "The ANSI code for reset: \033[0m"
    fi

fi
