#!/bin/bash
[[ -z $TMPDIR ]] && echo 'TMPDIR not set, exiting ...' && exit 1

if [[ -f "$1" ]]; then
    exec_f=$(basename -s ".c" "$1")
    gcc -w -g "${@:2}" -o "$TMPDIR/$exec_f" "$1" && gdb -q "$TMPDIR/$exec_f"
    [[ -f "$TMPDIR/$exec_f" ]] && rm -f "$TMPDIR/$exec_f"
else
    echo "File doesn't exist!"
fi
