#!/bin/bash
if [[ -f "$1" ]]; then
    exec_f=$(basename -s '.c' "$1")
    exec_d=${TMPDIR:-/tmp}

    gcc -w -g "${@:2}" -o "$exec_d"/"$exec_f" "$1" && gdb -q "$exec_d"/"$exec_f"
    [[ -f "$exec_d"/"$exec_f" ]] && rm -f "$exec_d"/"$exec_f"
else
    echo "File doesn't exist!"
fi
