#!/bin/bash
set -euo pipefail
_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {
    [[ -z $TMPDIR ]] && TMPDIR='/tmp'

    [[ $# -eq 0 ]] && search="$(echo | ${DMENU} 'Urban Dictionary:' | sed 's/ /%20/g')" || search="$1"

    [[ -z $search ]] && exit 1

    curl -s "https://api.urbandictionary.com/v0/define?term={$search}" | jq '.' | grep --color=always definition | awk 'BEGIN {RS="definition"; ORS=""} {print $0""++i}' > $TMPDIR/urban-dic

    n=$(wc -l < $TMPDIR/urban-dic)
    cat /dev/null > $TMPDIR/urban-dic.txt

    for i in $(eval echo {1..$n}p)
    do
        sed -n $i $TMPDIR/urban-dic | sed -r "s/\x1B\[[0-9;]*[a-zA-Z]//g" >> $TMPDIR/urban-dic.txt
    done
    notify-send -t 0 "$search" "$(cat $TMPDIR/urban-dic.txt | ${DMENU} "$search" | cut -d ':' -f 2 | grep -o "\".*\"")"
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
