#!/usr/bin/env bash
# The famous "get a menu of emojis to copy" script.

set -euo pipefail
_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"

if [[ -f "${_path}/_dm-helper.sh" ]]; then
# shellcheck disable=SC1090,SC1091
    source "${_path}/_dm-helper.sh"
else
# shellcheck disable=SC1090
    echo 'No helper-script found'
fi

# Script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {
    emoji_file="$XDG_DATA_HOME/dm-emoji/emoji_list"

    # Get user selection via dmenu from emoji file.
    chosen="$(cut -d ';' -f1 "$emoji_file" | ${DMENU} 'Select emoji: ' | sed 's/ .*//')" || exit 1

    xdotool type "$chosen"
    printf "%s" "$chosen" | xclip -selection clipboard
    notify-send -u low "'$chosen' copied to clipboard." 
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
