#!/bin/sh

# The famous "get a menu of emojis to copy" script.

emoji_file="$XDG_DATA_HOME/dm-emoji/emoji_list"

# Get user selection via dmenu from emoji file.
chosen="$(cut -d ';' -f1 "$emoji_file" | dmenu -i -l 20 -fn Mononoki-14 | sed "s/ .*//")"

# Exit if none chosen.
[ -z "$chosen" ] && exit


paste () {
    if [[ "$(xdotool getwindowfocus getwindowname)" == "hadouken@archrs:~" ]] ; then
        xdotool key "ctrl+shift+v"
    else
        xdotool key "ctrl+v"
    fi
}
# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ]; then
	xdotool type "$chosen" 
else
	printf "%s" "$chosen" | xclip -selection clipboard && paste
	notify-send -u low "'$chosen' copied to clipboard." 
fi
