#!/usr/bin/env bash
set -euo pipefail

_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
    # shellcheck disable=SC1090,SC1091
    source "${_path}/_dm-helper.sh"
else
    # shellcheck disable=SC1090
    echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"


main() {
    search_term=$(echo | ${DMENU} "Search:")
    look $search_term "$word_file" | ${DMENU} 'Matches: ' | tr -d '\n' | xclip -sel c
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
