#!/bin/bash
declare -A f_list

for font in $(fc-list | awk '{print $1}'| sed 's/://g' | grep -i "\.ttf$\|\.otf$\|\.TTF$")
do
    #index=$(echo "$font" | rev | cut -d'/' -f 1 | cut -d '.' -f 2 | rev)
    index=$(basename $font | sed 's/\..3$//')
    f_list[$index]="$font"
done

choice="$(printf "%s\n" ${!f_list[@]} | dmenu -i -l 20 -fn "Mononoki-nerd-font" -p 'Fonts: ')"
[[ -n $choice ]] && display "${f_list[$choice]}"
