#!/bin/bash
#BASH script to serve files
#Usage: serve <filename>
#for root then port 80 is used, else port 8888

file="$1"
#TODO: split fileNAME from file
port="8888"
addr="$(ip route get 1.2.3.4 | cut -d' ' -f 7)"

#TODO: Add dynamic ports

[[ $UID = 0 ]] && port=80 #I know it's a bad idea

if [[ ! -f "$file" ]]; then
	echo "File does not exist";
	exit 1;
fi


date=$(date +"%a, %d %b %Y %H:%M:%S %Z")

size=`du -b "$file" | awk '{print $1}'`
header="HTTP/1.1 200 OK\r\n\
Server: Netcat File Server\r\n\
Date: $date\r\n\
Content-type: application/octet-stream\r\n\
Content-Length: $size\r\n\
Connection: close\r\n\
Content-Disposition: attachment; filename=\"$file\"
Last Modified:$date\r\n\r\n";
shout(){
	printf "%s$header";
	cat "$file"
	printf "%s\c"
}

#TODO: Include Error if port is in use
while true
do
    trap 'break' SIGINT
    printf "\033[1;32mServing $file ($size bytes) with ❤️  on http://$addr:$port\033[0m\n"
    shout | nc -l -p $port
done

#TODO: Read about file descriptors
