#!/bin/bash
log_dir=${XDG_CACHE_HOME:=$HOME/.cache}
for i in "$@"
do
    if [[ -f "$i" ]]; then
        nohup xdg-open "$i" > "$log_dir/open.$(basename "$i").log" 2>&1 &
    # for viewing directories in cli file manager
    elif [[ -d "$i" ]]; then
        xdg-open "$i"
    else
        printf "\033[1;31m[ERROR]: %s\033[0m\n" 'File not found !'
    fi
done
