#!/bin/bash
#ftype=${1?Error: No file provided.}
[[ -z $TMPDIR ]] && TMPDIR='/tmp'
ftype=${1##*.}

cppr () {
    fname=$(basename -s ".cpp" "$1")
    g++ -Wall -Wextra -Werror -O2 -pedantic -o "$TMPDIR/$fname" $1 && "$TMPDIR/$fname"
    [[ -f "$TMPDIR/$fname" ]] && rm -f "$TMPDIR/$fname"
}

cr() {
    fname=$(basename -s ".c" "$1")
    gcc -Wall -Wextra -Werror -O2 -std=c99 -pedantic $1 -o "$TMPDIR/$fname" && "$TMPDIR/$fname" ${@:2}
    [[ -f "$TMPDIR/$fname" ]] && rm -f "$TMPDIR/$fname"
}

case $ftype in
    cpp)
        cppr "$@" ;;
    c)
        cr "$@" ;;
    *)
        echo 'Unknown file format.' ;;
esac
