#!/bin/bash
die() {
    echo "${1:-Some Error Occured.}"
    exit 1
}

[[ -z "$1" ]] && die 'No File Provided.'
[[ -f "$1" ]] || die "File Doesn't Exist."

[[ -z $TMPDIR ]] && TMPDIR='/tmp'
ftype=${1##*.}

cpprun() {
    fname=$(basename -s ".cpp" "$1")
    g++ -Wall -Wextra -Werror -O2 -pedantic -o "$TMPDIR/$fname" $1 && "$TMPDIR/$fname"
    [[ -f "$TMPDIR/$fname" ]] && rm -f "$TMPDIR/$fname"
}

crun() {
    fname=$(basename -s ".c" "$1")
    gcc -Wall -Wextra -Werror -O2 -std=c99 -pedantic $1 -o "$TMPDIR/$fname" && "$TMPDIR/$fname" ${@:2}
    [[ -f "$TMPDIR/$fname" ]] && rm -f "$TMPDIR/$fname"
}

case $ftype in
    cpp)
        cpprun "$@" ;;
    c)
        crun "$@" ;;
    java)
        java "$@" ;;
    py)
        python "$@" ;;
    *)
        die 'Unknown file format.' ;;
esac
