#!/usr/bin/env bash
data_dir="${XDG_DATA_HOME:-$HOME/.local/share}/wal"
cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/wal"

showhelp() {
	cat <<- EOM
	Set wallpaper and apply colorscheme extracted from it (using pywal) to other programs.
	Usage: $(basename $0) [-fh]
	       $(basename $0) [image_dir/image]

	If no wallpaper provided, choose one randomly from favorities file. If a
	directory of images is provided, keep choosing randomly from it until one
	wallpaper is selected by user.
	Favorites file -> $data_dir/favorites.txt

	-f -> save the current wallpaper to favorites
	-h -> show this help message
	EOM
}

while getopts "hfr" opt; do case "$opt" in
    f) sed -e 's/$/\n/' "$cache_dir"/wal >> "$data_dir"/favorites.txt
       sort "$data_dir"/favorites.txt | uniq > "${TMPDIR:-/tmp}"/wal-fav
       cp /tmp/wal-fav "$data_dir"/favorites.txt
       exit 0
       ;;
    r) wal="$(sed -e 's/$/\n/' "$cache_dir"/wal)" ;;
    h) showhelp && exit 0 ;;
    ?) showhelp && exit 1 ;;
esac done

# [[ -n "$1" ]] && wal="$1" || wal="$(shuf "$data_dir/favorites.txt" -n 1)"
if [[ -z "$wal" ]]; then
    [[ -n "$1" ]] && wal="$1" || wal="$(fzf < "$data_dir/favorites.txt")"
fi

set() {
    wal -n --recursive -i "$1" --cols16 --backend colorz
    img="$(cat "$cache_dir"/wal)"

    if [[ "$XDG_SESSION_TYPE" == 'x11' ]]; then
        nitrogen --set-zoom-fill "$img" &> /dev/null &
    elif [[ "$XDG_SESSION_TYPE" == 'wayland' ]]; then
        hyprctl hyprpaper preload "$img" &> /dev/null
        hyprctl hyprpaper wallpaper "eDP-1, $img" &> /dev/null
        hyprctl hyprpaper unload "$img" &> /dev/null
    else
        echo "[ERROR]: Unsupported session."
        exit 1
    fi
}

if [[ -d "$wal" ]]; then
    # iterate as long as condition is false
    until [[ "$choice" == 'y' ]]; do
        set "$wal"
        read -r -n 1 -p 'Like this colorscheme ? (y/n)' choice
        printf "\n\n"
    done
elif [[ -f "$wal" ]]; then
    set "$wal"
else
    echo "[Error]: '$wal' is not a file or directory."
fi

### Program Integration ###
# firefox
# semicolon is required after the last command in a command group
# pgrep -x firefox > /dev/null && { pywalfox update || echo "Can't update firefox theme !"; }

# dunst
pgrep -x dunst > /dev/null && killall dunst

# StartTree
starttree.py &> /dev/null
